name: PublishDocumentation

on: [push]

jobs:
  deploy_docs:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        args: "--theme fullwidth --author S5TF Team --author_url http://s5tf-team.github.io --github_url https://github.com/s5tf-team/"
